### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by qiukeren** [zekroTJA/timedmap#4]
```

fatal error: concurrent map writes

goroutine 53 [running]:
runtime.throw(0x21d9a37, 0x15)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc00059a5a8 sp=0xc00059a578 pc=0x56b952
runtime.mapdelete(0x204f0a0, 0xc00032e180, 0xc00059a638)
        /usr/local/go/src/runtime/map.go:702 +0x46e fp=0xc00059a608 sp=0xc00059a5a8 pc=0x544c6e
github.com/zekroTJA/timedmap.(*TimedMap).expireElement(0xc000618040, 0x2000940, 0xc007e1d690, 0x0, 0xc006694300)
        /root/go/pkg/mod/github.com/zekro!t!j!a/timedmap@v1.3.0/timedmap.go:177 +0xc5 fp=0xc00059a660 sp=0xc00059a608 pc=0x10756e5
github.com/zekroTJA/timedmap.(*TimedMap).cleanUp(0xc000618040)
        /root/go/pkg/mod/github.com/zekro!t!j!a/timedmap@v1.3.0/timedmap.go:190 +0x1a9 fp=0xc00059a758 sp=0xc00059a660 pc=0x10758a9
github.com/zekroTJA/timedmap.New.func1(0xc0000cc3c0, 0xc000618040)
        /root/go/pkg/mod/github.com/zekro!t!j!a/timedmap@v1.3.0/timedmap.go:62 +0x97 fp=0xc00059a7d0 sp=0xc00059a758 pc=0x1075f77
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00059a7d8 sp=0xc00059a7d0 pc=0x5a1ce1
created by github.com/zekroTJA/timedmap.New
        /root/go/pkg/mod/github.com/zekro!t!j!a/timedmap@v1.3.0/timedmap.go:58 +0xc5

```

**Comment by qiukeren** [comment]
离谱的是 我自己跑bench跑不出来这个结果

it is confusing i can't provide it with main.


```

package main

import (
	"github.com/remeh/sizedwaitgroup"
	"github.com/zekroTJA/timedmap"
	"math/rand"
	"time"
)

func main() {
	tm := timedmap.New(5 * time.Millisecond)
	rand.Seed(time.Now().UnixNano())

	swg := sizedwaitgroup.New(80)
	for i := 0; i < 5000000000; i++ {
		swg.Add()
		go func(i int) {
			defer swg.Done()
			//k := RandStringRunes(10)
			k := "a"
			tm.Set(k, rand.Int31(), 3*time.Millisecond)
		}(i)
	}
	swg.Wait()
}
```
